### ISSUE TITLE
Passing HTML data directly instead of providing a url ?

### ISSUE THREAD

**Issue by ezzdev** [scotteh/php-goose#109]
Hi

Can i pass HTML data directly instead of providing a url ?

Thank you

**Comment by ducwp** [comment]
$article = $goose->extractContent('https://google.com/', $html);

**Comment by cabohe** [comment]
Hi, sure this is late.... but you can pass second param to extractContent() with the html:

$goose->extractContent('https://www.example.com',$content);

Works Ok!

**Comment by rcoenen** [comment]
so what does it do with 'https://www.example.com' before it tries to extract $content ?
Just ignores it?

**Comment by rcoenen** [comment]
Ah ok yes so this works, you need to pass a valid url in as 1st argument but it is further ignored.

` $article_extracted = $goose->extractContent("http://foo/bar", $rawHTMLstr);
`

**Comment by hashborgir** [comment]
I came by looking to do the same, so poked at the code and here it is. If you don't provide raw html, it uses Guzzle to make a request, otherwise parses the raw html.

```
    public function crawl(string $url, string $rawHTML = null): ?Article {
        $article = new Article();

        $parseCandidate = Helper::getCleanedUrl($url);

        $xmlInternalErrors = libxml_use_internal_errors(true);

        if (empty($rawHTML)) {
            $guzzle = new \GuzzleHttp\Client();
            $response = $guzzle->get($parseCandidate->url, $this->config()->get('browser'));
            $article->setRawResponse($response);
            $rawHTML = $response->getBody()->getContents();
        }

        // Generate document
        $doc = $this->getDocument($rawHTML);
```
