### ISSUE TITLE
Why replace headings with \n?

### ISSUE THREAD

**Issue by jwahdatehagh** [scotteh/php-goose#114]
Hi!

Lovely package - but i don't understand the reasoning behind stripping the page of it's headings (and thus the outline structure):

https://github.com/scotteh/php-goose/blob/78599a1bac6af271ce8bc4fab6cdce76c1d3feca/src/Modules/Formatters/OutputFormatter.php#L174

Would you consider a PR that makes this (and also stripping `strong` and `em` tags) optional?

**Comment by cabohe** [comment]
Same problem here.... theoretically, calling the **getHtmlArticle()** function those TAGS are not replaced, but on my side the only difference with **getCleanedArticleText()** is that the paragraphs are preserved
