### ISSUE TITLE
How to deal with timeouts?

### ISSUE THREAD

**Issue by rcoenen** [scotteh/php-goose#117]
Uncaught exception: cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.thenewstribune.com/news/business/article253829213.html

**Comment by rcoenen** [comment]
I have set browser->connect_timeout to 10... then why os cURL reporting a timeout of 60001 milliseconds?
Seems the configurable timeout is not passed onto cURL?

When mass-scraping sites in aurtomated process you obviously will run into this situation at some point.
We need a graceful way of handling this.

**Comment by hashborgir** [comment]
Same error on same domain I got.
