### ISSUE TITLE
Incompatible with laravel 9 due to symfony/css-selector version requirement

### ISSUE THREAD

**Issue by pko734** [scotteh/php-goose#119]
$ composer require scotteh/php-goose
Using version ^1.1 for scotteh/php-goose                                            
./composer.json has been updated
Running composer update scotteh/php-goose
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - scotteh/php-dom-wrapper[2.0.0, ..., 2.0.1] require symfony/css-selector ^4.0 || ^5.0 -> found symfony/css-selector[v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but it conflicts with your root composer.json require (^6.0).
    - scotteh/php-goose 1.1.0 requires scotteh/php-dom-wrapper ^2.0 -> satisfiable by scotteh/php-dom-wrapper[2.0.0, 2.0.1].
    - Root composer.json requires scotteh/php-goose ^1.1 -> satisfiable by scotteh/php-goose[1.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by scotteh** [comment]
Fixed in an upstream dependency.
