### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: DateTime::__construct(): Argument #1 ($datetime) must be of type string

### ISSUE THREAD

**Issue by hashborgir** [scotteh/php-goose#123]
Getting this error.

`PHP Fatal error:  Uncaught TypeError: DateTime::__construct(): Argument #1 ($datetime) must be of type string, int given in /vendor/scotteh/php-goose/src/Modules/Extractors/PublishDateExtractor.php:115`

I've had to explicitly cast $date to string in line 115:

`$dt = new \DateTime("$date");`

enclosed in Quotes "typecasts" (not really) but enclosing it in a string does the job, so it has to a string which seems to work. Since I'm not interested in extracted date, I can by pass this.

**Comment by jtomek** [comment]
Guys, this needs to be addressed. There is a pending hotfix since December. https://github.com/scotteh/php-goose/pull/122

Please accept it.
