### ISSUE TITLE
Deprecated: mb_convert_encoding()

### ISSUE THREAD

**Issue by rcoenen** [scotteh/php-goose#124]
Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /vendor/scotteh/php-dom-wrapper/src/Document.php on line 247

**Comment by scotteh** [comment]
Fixed upstream. Run `composer update`.
