### ISSUE TITLE
Wrong Title for Article - Python Goose gets the correct one

### ISSUE THREAD

**Issue by mrbarletta** [scotteh/php-goose#14]
First, thanks for the library! :)

Parsing this article :  http://www.bbc.com/news/magazine-32689533
Real Title: Trounced by a brain-training octogenarian
php-goose Title: training octogenarian
python-goose Title:  Trounced by a brain-training octogenarian

**Comment by scotteh** [comment]
Cheers for report. The python goose methods handle titles more gracefully than the existing ones. I've just ported them over more-or-less as is in 1edaa35.

**Comment by mrbarletta** [comment]
Great! - 
Just tested and it works fine!.

Next: Meta_description ;)

With the same article, 
php-goose: empty
pythong goose: 'Experts debate the value of brain games, but Adam Shaw was surprised to be beaten at a simple arithmetic test by a woman double his age.'

**Comment by scotteh** [comment]
Nice find, document cleaner was being a tag aggressive! 

See 7212c6135d

**Comment by mohamedhassan1** [comment]
i have problem with php-goose! Can You help me  if You are don't mind  ^ ^ ?!
i use it with laravel 4.2 but not run !
 these images about what i do !
1------
![1](https://cloud.githubusercontent.com/assets/13078585/8392913/d40a7806-1cf9-11e5-8a0c-2eca7243577e.JPG)
2-----
![2](https://cloud.githubusercontent.com/assets/13078585/8392915/e9d411c4-1cf9-11e5-936f-38a5b1138be0.JPG)
3-----
![3](https://cloud.githubusercontent.com/assets/13078585/8392916/ef9538cc-1cf9-11e5-94d5-f68c5124b55e.JPG)

thanks ...

**Comment by scotteh** [comment]
@mohamedhassan1 You've placed code outside your showWelcome() method - it's causing the error you're seeing, try something like:

``` php
public function showWelcome()
{
	$goose = new GooseClient();
	$article = ...
	// etc..
}
```

Laravel has it's own autoloader. Remove the vendor/autoload.php line.

Best create a new issue in future.
