### ISSUE TITLE
Division by 0 in NodeCommonTrait.php

### ISSUE THREAD

**Issue by Linksku** [scotteh/php-goose#16]
$linkDivisor = $numberOfLinkWords / count($words);

Division by 0 occurs when the article has an empty link in a node without words. E.g. `<div><a></a></div>`

Found an example:
````
<div id="login-wrapper-btn" class="pull-left">
<a href="/"><img src="http://www.allkpop.com/img/logo-akp-clear@2x.png"></a>
</div>
````

**Comment by scotteh** [comment]
Cheers for the bug rep - should fix the issue you're seeing.
