### ISSUE TITLE
Bug in DocumentCleaner::convertToParagraph()

### ISSUE THREAD

**Issue by Linksku** [scotteh/php-goose#17]
PHP Goose turns this:
```
Ah, so this must be the song that <b>Yang Hyun Suk </b>was teasing us for with those Instagram videos! <a href="http://allkpop.com/artisttag/big-bang" target="_blank">Big Bang</a> will be coming back with a new song titled "<b>Let's Not Love</b>"!
```
Into this:
```
Ah, so this must be the song thatBig BangYang Hyun Sukwas teasing us for with those Instagram videos! will be coming back with a new song titled "Let's Not Love"!
```

Evidently, the `<a>` is being misplaced. I narrowed down the problem to `DocumentCleaner::convertToParagraph()`. I'm guessing it's in `getReplacementNodes()`, but I can't find the exact line the bug's occurring. Please look into this.

**Comment by scotteh** [comment]
fee3c06046965bf586a669ccbd92e099d8d3a1e9 fixes this - a dependency was also updated so you'll need to update your composer packages.
