### ISSUE TITLE
Call to undefined method DOMProcessingInstruction::is()

### ISSUE THREAD

**Issue by dsposito** [scotteh/php-goose#18]
After installing via composer and importing `use Goose\Client as GooseClient;`, I receive the following fatal error from the code snippet below:

```
Call to undefined method DOMProcessingInstruction::is()
.../vendor/scotteh/php-dom-wrapper/src/Traits/TraversalTrait.php @ line 401
```

```
$goose = new GooseClient();
$goose->extractContent('http://sports.yahoo.com/news/who-s-new-england-s-most-beloved-hero--tom-brady--or-his-lawyer-071009117.html');
```

**Comment by scotteh** [comment]
Thanks for the bug report. Fixed the issue you picked up in dev-master, also required a change to the scotteh/php-dom-wrapper dependency.

**Comment by dsposito** [comment]
Wow, awesome - thanks so much! I'll try again tonight and confirm.

**Comment by dsposito** [comment]
Confirmed - I'm no longer getting any errors. Thanks!
