### ISSUE TITLE
Error: "Couldn't fetch DOMWrap\Element. Node no longer exists"

### ISSUE THREAD

**Issue by dsposito** [scotteh/php-goose#20]
`Error: "Couldn't fetch DOMWrap\Element. Node no longer exists" in php-dom-wrapper/src/Traits/NodeTrait.php @ line 32`

Including Google as the referer gives access to an article's entire contents (bypassing the paywall prompt) on WSJ.com.

The `extractContent()` method is throwing the above error when I include the Guzzle headers param:

```
$goose = new GooseClient(array(
    'browser' => array(
        'headers' => array('Referer' => 'http://www.google.com'),
    ),
));
$article = $goose->extractContent("http://www.wsj.com/articles/oculus-lines-up-more-virtual-reality-content-1443139611");
```

**Comment by scotteh** [comment]
Cheers for picking this up - just pushed a fix. fd1cd1cc0035f9fddcd8e71c1248f27fa292c4d9

**Comment by dsposito** [comment]
Confirmed. Thank you! :+1:
