### ISSUE TITLE
Problems with encoding (Fixed) / Article contents not being extracted

### ISSUE THREAD

**Issue by d3sire** [scotteh/php-goose#24]
When I am extracting article from Russian websites every symbol is displayed as question marks. I tried opening with different encoding but with no luck.
Configuration 

```
$goose = new GooseClient(['language' => 'ru','image_max_bytes' => 0]);

```

Website for example:

```
$article = $goose->extractContent('http://www.kommersant.ru/doc/2824645');
```

**Comment by scotteh** [comment]
@d3sire Fix this up :) The issue wasn't in php-goose itself, but rather the php-dom-wrapper dependency which was failing to detect and convert the charset correctly. Running `composer update` should fix the encoding issue.

Looking at the results for the URL you mentioned this may of uncovered a bug within php-goose and it not selecting the article text. Let me know how it goes for you.

**Comment by d3sire** [comment]
Thanks @scotteh  encoding fix works great. The article from my previous example was extracted great.
But when I tried [another one](http://www.gazeta.ru/politics/2015/10/06_a_7797395.shtml) it fails to parse and return empty string.
