### ISSUE TITLE
h1,h2...h6 omitting from result

### ISSUE THREAD

**Issue by tamimibrahim** [scotteh/php-goose#25]
I am trying to extract article from a page. php-goose doing well for this purpose but it is omitting h1,h2,h3.. etc title tag from result. Am I missing some configuration?

**Comment by scotteh** [comment]
@tamimibrahim It won't explicitly remove heading tags, though it may if they're deemed unimportant or unwanted/ads. Do you have an example URL?

**Comment by tamimibrahim** [comment]
Hi thanks for reply. Actually It is not working for most urls. For example if you check this url --> https://www.quicksprout.com/2015/10/19/6-psychological-principles-that-influence-reader-loyalty/ you should see that it isn't returning any h1 or h2 tag value.
