### ISSUE TITLE
$article->getAllImages(); always comes up empty

### ISSUE THREAD

**Issue by AdriaanQuevis** [scotteh/php-goose#28]
Hi,

Thanks for the great code. Just one issue i keep having is that 

$article->getAllImages(); always returns empty, i can't seem to find a fix for it, do you have any idea or suggestion?

When i set fetch all images to true i get the following fatal error:
Fatal error:  Call to undefined method GuzzleHttp\Exception\RequestException::getStatusCode() in /home/taggrs5/adriaan/test/vendor/scotteh/php-goose/src/Images/ImageUtils.php on line 121

Thanks.

**Comment by scotteh** [comment]
Do you have an example URLs? Wasn't able to replicate this issue trying a handful of different ones.

**Comment by Lucascvs** [comment]
Hey,
This page (for example) raises this exception, for me : http://mobile.nytimes.com/2016/04/28/world/americas/colombia-farc-child-soldiers.html.
It seems to be tied to redirects, but I'll investigate this a bit further before making this statement.
