### ISSUE TITLE
Fatal error: Call to a member function getStatusCode() on null in src/Images/ImageUtils.php on line 124

### ISSUE THREAD

**Issue by yashari01** [scotteh/php-goose#29]
I always get this error 
Fatal error: Call to a member function getStatusCode() on null in /Applications/XAMPP/xamppfiles/htdocs/fiverr/gooser/vendor/scotteh/php-goose/src/Images/ImageUtils.php on line 124

when testing with the same code in github page

**Comment by scotteh** [comment]
Possible an issue with the version of guzzle being used. Which version of the guzzlehttp/guzzle package is installed?

**Comment by scotteh** [comment]
Looks to be the same issue as #28.

**Comment by techappg** [comment]
facing same issue
