### ISSUE TITLE
Improve PublishDateExtractor

### ISSUE THREAD

**Issue by cdubz** [scotteh/php-goose#32]
Currently [PublishDateExtractor](https://github.com/scotteh/php-goose/blob/master/src/Modules/Extractors/PublishDateExtractor.php) only uses [GetDateFromURL](https://github.com/scotteh/php-goose/blob/master/src/Modules/Extractors/PublishDateExtractor.php#L30) to try to find a publish date for the article.

One example of where this is a problem is with the following URL: http://www.nst.com.my/news/2016/05/147553/two-chapters-rcep-agreement-conclude-june-mustapa

In this case the article publish date is erroneously retrieved as 2016-05-14 because of the odd URL convention used. There is actually no other good source of information in this particular example, but I do see a number of nodes with `itemprop="datePublished"` in other articles. Searching for dates in those nodes could yield much better results.

I'd be happy to do a PR for this if there is interest.

**Comment by scotteh** [comment]
The date extractor could definitely use some improvements. If you're keen enough to implement some, I'd be more than happy to merge them in.

**Comment by cdubz** [comment]
Will do. I have begun using this library a bit so I have already started to implement this through an external hook. I'll finish that up and then port it in to a fork and PR.

Using my own data set, I have the found the following seven potential points to check (as node identifiers for DOMWrap\Document->find()):

- `meta[itemprop="datePublished"]`
- `time[itemprop="datePublished"]`
- `meta[property="article:published_time"]`
- `meta[name="DC.date.issued"]`
- `meta[name="dc.date"]`
- `script[type="application/ld+json"]`
- `meta[name="parsely-page"]`

There are surely lots of other conventions, so I'm also trying to think of other generalized ways to do this, but this is where I am starting for now.
