### ISSUE TITLE
Are crawl only available for english pages

### ISSUE THREAD

**Issue by abdielcs** [scotteh/php-goose#33]
I try with a lot of spanish pages and the main text are always null. Is that the expected behavior?

**Comment by scotteh** [comment]
This may be related to the stopwords list for Spanish. In the configuration I assume you're setting the language to 'es'?

**Comment by abdielcs** [comment]
I see, problem resolved, so , is there any way to do it without specify the language?

**Comment by scotteh** [comment]
Not currently, I'm re-opening this as a task to add auto stopword loading based on the pages language.

**Comment by abdielcs** [comment]
OK, I think that should be the default behavior unless some specific language has been requested.

**Comment by scotteh** [comment]
This should now be fixed in dev-master.
