### ISSUE TITLE
It does not work with Chinese. Always return null cleaned article text.

### ISSUE THREAD

**Issue by liyadongcn** [scotteh/php-goose#36]
i already updated the composer as you said. It does not work with Chinese. Always return null cleaned article text.
sample link :http://news.sina.com.cn/c/2016-07-06/doc-ifxtwitr1604022.shtml

i tried to modify the config like
 $goose = new GooseClient([
                    'language' => 'zh',  
            ]);
Not working.

**Comment by ChubV** [comment]
ping
