### ISSUE TITLE
Not working on some websites eg: wikihow

### ISSUE THREAD

**Issue by tuhinte** [scotteh/php-goose#38]
Getting null when trying to get article from wikihow. eg: http://www.wikihow.com/Drive-in-Australia

**Comment by dragonattack** [comment]
Seems like layout of wikihow is hard to process. `$article->getCleanedArticleText()` still returns null or small snippets instead of full article text.
For example: https://www.wikihow.com/Tell-if-Your-Boyfriend-Is-Gay
