### ISSUE TITLE
Get content encoding

### ISSUE THREAD

**Issue by doublex** [scotteh/php-goose#43]
Hello,
I can get the html by calling: `getRawHtml()`.
Is there a chance to get the content-encoding?
My problem: I would need the HTML as UTF8 (even if the website uses a differnt encoding)
Thanks a lot!
Markus

**Comment by scotteh** [comment]
0612f1263dbab62d389b505bc448b21f941a6a1b fixes this and adds the getRawResponse() method which returns Guzzles response (`Psr\Http\Message\ResponseInterface` compatible interface). You can access the headers via the getHeaders() method.

Also bumped the latest version to 0.5.0.
