### ISSUE TITLE
Website issue: Slate.com

### ISSUE THREAD

**Issue by crscheid** [scotteh/php-goose#44]
Hi there, love the work. Been trying to paw through the code to figure out how it works so I can hopefully contribute. I might have found an interesting use case where the current processing doesn't work.

I've checked multiple links on slate.com's website. None of their pages seem to pass the isOkToBoost check in ContentExtractor - leading to a situation where the parent node cannot be identified. For example check here:
 http://www.slate.com/blogs/browbeat/2017/01/18/will_and_grace_is_returning_to_nbc_for_a_10_episode_revival.html

BTW, please let us know how we can best contribute sites that seem to have issues. As I get more familiar with the code, I'll certainly submit pull requests for any solutions that I find.

**Comment by scotteh** [comment]
It does struggle with small paragraphs of text nested a few or more nodes from a common parent - quite possibly whats happening here.

I'll leave this open for now, add any other links you come across.

**Comment by crscheid** [comment]
Yeah, I built a wrapper around your library to handle this case since the flow of your processing makes some cleaning assumptions before the case could be detected. Essentially it comes down to a sibling check. If you're curious, you can see my wrapper code here along with the sibling check.  (https://github.com/crscheid/php-article-extractor/blob/master/src/ArticleExtractor.php#L162) 

I'll give it some more thought and see if there is a way to integrate it more cleanly into goose. Would rather have a single library instead of a wrapper around yours to be honest.

**Comment by DaveChild** [comment]
Here's another example:

https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/bulletins/crimeinenglandandwales/june2017
