### ISSUE TITLE
Does PHP-Goose support on pages with other languages than English?

### ISSUE THREAD

**Issue by korusdipl** [scotteh/php-goose#45]
Thank you for distributing this project for free.
However, I have some trouble extracting cleanedTexts from Korean online news article pages.

The example URL is http://v.media.daum.net/v/20170126143603318
My settings were php-goose : dev-master on composer.json, and the code is the following.
I have PHP 7.1 with me. The following is what I did.

```
require "vendor/autoload.php";
use Goose\Client as GooseClient;
$goose = new GooseClient(['language' => 'ko']);
$article = $goose->extractContent("http://v.media.daum.net/v/20170126143603318");
$title = $article->getTitle();
$articleText = $article->getCleanedArticleText();
```

Unfortunately, I get NULL from $articleText. 
Your assistance is in need.
Thank you.

**Comment by scotteh** [comment]
Largely untested with languages other than English. Curious to hear if you've had much success.

**Comment by cnsaturn** [comment]
@korusdipl @scotteh 

Currently in class [StopWords#L88](https://github.com/scotteh/php-goose/blob/master/src/Text/StopWords.php#L88):

```php
// CJK words should be taken further care of.
$candidateWords = explode(' ', $strippedInput);
``` 

When dealing with CJK words, Chinese or Korean in this case, [stop word counting logic](https://github.com/scotteh/php-goose/blob/master/src/Text/StopWords.php#L88) will always fail, since there is no space between two CJK words. This is linguistic dependent.

For CJK words, I suggest a quick fix for this (UNTESTED)?

```php
preg_match_all("/./u", $strippedInput, $candidateWords);
$candidateWords = $candidateWords[0];
```

**Comment by scotteh** [comment]
CJK is not something I'm really familiar with. However the string would still need to be broken up into 'words' - a CJK tokeniser could achieve this. There are some out there for other languages, not sure how accurate they are.

**Comment by Lucassifoni** [comment]
Hello,
While it doesn't address your issue related to CJK, I have had a great success rate last year while extracting 6200 articles in French, but more failures than the ~4200 English articles set I also used.
While keeping in mind that failures were often related to markup issues, I had some evidence that non-english languages could use improvements.
(And, how can we help ? I'd be willing to help for French, for instance.)

**Comment by scotteh** [comment]
Always happy to accept PR's. The primary difference between all the languages are the stopwords, they may need to be modified for French to reduce the failure rates.

I'd be curious to see a list of articles you had issues with.

**Comment by Lucassifoni** [comment]
Unfortunately, I lost this project's db after a hard drive crash last summer (yes, in 2016).
I still have all those articles uris (kept online), I could try to re-extract them to provide stats on this particular issue.
I'll keep you updated in case I find the time to do this.
