### ISSUE TITLE
SSL verify option

### ISSUE THREAD

**Issue by spagu** [scotteh/php-goose#53]
Hi I am doing exact example as written in documentation against ssl domain and I am getting fatal error of:

`Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187 `

can you add documentation how to fix it ? thanks.

**Comment by scotteh** [comment]
This is a general php/curl related issue. You'll need to update [curl.cainfo](http://php.net/manual/en/curl.configuration.php#ini.curl.cainfo) in your php.ini.
