### ISSUE TITLE
Argument 1 passed to Goose\Article::setRawResponse() must be an instance of Goose\Psr\Http\Message\ResponseInterface

### ISSUE THREAD

**Issue by andreasjacobsen93** [scotteh/php-goose#55]
I get the following when running the library:

Message: Argument 1 passed to Goose\Article::setRawResponse() must be an instance of Goose\Psr\Http\Message\ResponseInterface, instance of GuzzleHttp\Message\Response given, called in /.../vendor/scotteh/php-goose/src/Crawler.php on line 48
File: /.../vendor/scotteh/php-goose/src/Article.php
Line: 367

Trace
#0 /.../vendor/scotteh/php-goose/src/Crawler.php(48): Goose\Article->setRawResponse(Object(GuzzleHttp\Message\Response))
#1 /.../vendor/scotteh/php-goose/src/Client.php(42): Goose\Crawler->crawl('https://lifehac...', NULL)
#2 /.../templates/content/reader.php(12): Goose\Client->extractContent('https://lifehac...')

**Comment by scotteh** [comment]
What version of guzzlehttp/guzzle are you using? It looks like you're trying to use an older version of guzzle.

**Comment by andreasjacobsen93** [comment]
0.5.0 from composer

**Comment by scotteh** [comment]
You'll need to either update Guzzle, or downgrade your php-goose version. All versions after 0.3.0 require Guzzle 6.*.
