### ISSUE TITLE
getimagesize(): Filename cannot be empty

### ISSUE THREAD

**Issue by atmediauk** [scotteh/php-goose#57]
Hi, just came across this issue. Initially I thought it was my php.ini settings but even after upping upload_max_filesize, post_max_size, max_execution_time and setting a date.timezone I was still getting the error.

What did work for me was editing Goose\Images\ImageUtils slightly.

I just added a extra if checks to `getImageDimensions` changing:

```
//this
    public static function getImageDimensions($filePath) {
        list($width, $height, $type) = getimagesize($filePath);

        return (object)[
            'width' => $width,
            'height' => $height,
            'mime' => image_type_to_mime_type($type),
        ];
    }

//to this
    public static function getImageDimensions($filePath) {
        if ($filePath) {
            list($width, $height, $type) = getimagesize($filePath);

            return (object)[
                'width' => $width,
                'height' => $height,
                'mime' => image_type_to_mime_type($type),
            ];
        }
    }
```

and also further down in `storeImagesToLocalFile` changing:

```
//this
        foreach ($localImages as $localImage) {
            $imageDetails = self::getImageDimensions($localImage->file);

            $locallyStoredImages[] = new LocallyStoredImage([
                'imgSrc' => $localImage->url,
                'localFileName' => $localImage->file,
                'bytes' => filesize($localImage->file),
                'height' => $imageDetails->height,
                'width' => $imageDetails->width,
                'fileExtension' => self::getFileExtensionName($imageDetails),
            ]);
        }

//to this

        foreach ($localImages as $localImage) {
            $imageDetails = self::getImageDimensions($localImage->file);

            if ($imageDetails) {
                $locallyStoredImages[] = new LocallyStoredImage([
                    'imgSrc' => $localImage->url,
                    'localFileName' => $localImage->file,
                    'bytes' => filesize($localImage->file),
                    'height' => $imageDetails->height,
                    'width' => $imageDetails->width,
                    'fileExtension' => self::getFileExtensionName($imageDetails),
                ]);
            }

        }
```

Hopefully thats the correct fix. Thanks again for the package. It seems awesome, very much looking forward to playing with it!

**Comment by atmediauk** [comment]
Oh it seems despite the edits getting rid of the error messages none of the images are now extracted. Do you have any ideas on what could be causing the original getimagesize issue?

**Comment by scotteh** [comment]
Do you have any example URLs?

**Comment by atmediauk** [comment]
Thanks, the URL I was trying is: ```http://www.bbc.co.uk/news/world-us-canada-40676882```

With this the ```$allImages``` returns an empty empty but the ```$image``` correctly returns one image. Also the ```$video``` array also seems to be empty.

Any ideas on why this could be :)

On the whole the package seems to working nicely though! Awesome work!

**Comment by scotteh** [comment]
Haven't been able to replicate this issue. Based on the error you're getting I suspect the issue lies in Goose\Images\ImageUtils::handleEntity() and it's call to tempnam() or sys_get_temp_dir(). What do either of these return for you?

**Comment by scotteh** [comment]
I suspect 2ca009c fixes this. Closing.
