### ISSUE TITLE
images are returns null data 

### ISSUE THREAD

**Issue by pratheepchowdhary** [scotteh/php-goose#59]
this is the link

http://www.ntrapp.tk/article/index.php?url=http://www.bbc.co.uk/news/world-us-canada-40676882

**Comment by scotteh** [comment]
Looks OK here, getting multiple images for that article. What version / config are you using?

**Comment by pratheepchowdhary** [comment]
Version 0.5 
and php code
<?php require('vendor/autoload.php'); use Goose\Client as GooseClient; $goose = new GooseClient([ // Fetch best image 'image_fetch_best' => true, // Fetch all images 'image_fetch_all' => true, // Guzzle configuration - All values are passed directly to Guzzle // See: http://guzzle.readthedocs.io/en/stable/request-options.html 'browser' => [ 'timeout' => 60, 'connect_timeout' => 30 ] ]); $url = $_GET["url"]; $article = $goose->extractContent($url); $title = $article->getTitle(); $metaDescription = $article->getMetaDescription(); $metaKeywords = $article->getMetaKeywords(); $canonicalLink = $article->getCanonicalLink(); $domain = $article->getDomain(); $tags = $article->getTags(); $links = $article->getLinks(); $videos = $article->getVideos(); $articleText = $article->getCleanedArticleText(); $entities = $article->getPopularWords(); $image = $article->getTopImage(); $allImages = $article->getAllImages(); $opengraph =$article->getOpenGraphData(); $myObj->title= $title ; $myObj->metaDescription= $metaDescription; $myObj->metaKeywords = $metaKeywords ; $myObj->cononicalLink=$canonicalLink ; $myObj->source= $domain; $myObj->tags= $tags; $myObj->link= $links ; $myObj->videos= $videos; $myObj->text= $articleText; $myObj->entities= $entities; $myObj->image= $image; $myObj->allimages= $allImages; $myObj->opengraphdata= $opengraph; echo json_encode($myObj); ?>

**Comment by pratheepchowdhary** [comment]
goose config

 $goose = new GooseClient([ // Fetch best image 'image_fetch_best' => true, // Fetch all images 'image_fetch_all' => true, // Guzzle configuration - All values are passed directly to Guzzle // See: http://guzzle.readthedocs.io/en/stable/request-options.html 'browser' => [ 'timeout' => 60, 'connect_timeout' => 30 ] ]);

**Comment by scotteh** [comment]
Tagged a new v0.6 release, updating to this should fix your issue.

**Comment by pratheepchowdhary** [comment]
Thank u so much

**Comment by pratheepchowdhary** [comment]
still same issue

image":{},"allimages":[{},{},{},{},{},{},{},{},{},{}]

**Comment by scotteh** [comment]
Have you got an example URL I could review?

**Comment by pratheepchowdhary** [comment]
http://www.ntrapp.tk/article/index.php?url=http://www.bbc.co.uk/news/world-us-canada-40676882

**Comment by pratheepchowdhary** [comment]
Hello please help me sir

**Comment by scotteh** [comment]
Could you confirm you're using v0.6? What does the following return for you?

``` php
$goose = new GooseClient();
$article = $goose->extractContent('http://www.bbc.co.uk/news/world-us-canada-40676882');
var_dump($article->getAllImages());
```

**Comment by pratheepchowdhary** [comment]
http://www.ntrapp.tk/cleaner/index.php
and result
array(0) { }
iam already using 0.6

**Comment by scotteh** [comment]
Woops, sorry, the snippet above should of read:

``` php
$goose = new GooseClient([
    'image_fetch_all' => true,
]);
$article = $goose->extractContent('http://www.bbc.co.uk/news/world-us-canada-40676882');
var_dump($article->getAllImages());
```

That config option is required to fetch all images.
