### ISSUE TITLE
Main image and images are always empty

### ISSUE THREAD

**Issue by AdriaanCo** [scotteh/php-goose#60]
Hi,

Im using php-goose with laravel, php-goose with default settings, whatever url i use it always returns no images.

I've already updated to latest versions, but doesnt resolve anything. Any suggestions? 

Thanks.

**Comment by scotteh** [comment]
The images will need to fit the minimum requirements to be considered.

You could try setting the following to remove any of these limitations:

``` php
$goose = new GooseClient([
    'image_min_bytes' => 0,
    'image_min_width' => 0,
    'image_min_height' => 0,
});
```

**Comment by pratheepchowdhary** [comment]
still same return empy images

**Comment by AdriaanCo** [comment]
I have tried that already, but same result, all empty. Sometimes the allImages array has items but the items itself are also empty.

**Comment by scotteh** [comment]
Do you have an example URL?

**Comment by pratheepchowdhary** [comment]
http://www.ntrapp.tk/article/index.php?url=http://www.bbc.co.uk/news/world-us-canada-40676882
