### ISSUE TITLE
Minimum requirements for for just article extractor

### ISSUE THREAD

**Issue by ClosetMonkey** [scotteh/php-goose#61]
I noticed that composer.json lists a couple http related requirements, presumably for crawler and general html fetching, but what are the minimum requirements of extracting article from existing content? Thanks

**Comment by scotteh** [comment]
If you're feeding in HTML just disable any image related fetching you could remove the following deps:

    "guzzlehttp/guzzle": "6.*",
    "jakeasmith/http_build_url": "0.1.*",

Example config to remove image fetching:

``` php
$goose = new GooseClient([
    'image_fetch_best' => false,
]);
```
