### ISSUE TITLE
Stopword lookupds should be case-insensitive

### ISSUE THREAD

**Issue by tott** [scotteh/php-goose#65]
Hi Scott,

I love this project. One thing I ran into however is 
https://github.com/scotteh/php-goose/blob/b2e6f998b749b8cd93dccbbadbd5609a2fad9fd2/src/Modules/Extractors/AdditionalDataExtractor.php#L142

I think it would make sense to make those lookups case insensitive such as so

`$words = array_udiff( $words, $ignoreWords, 'strcasecmp' );`

**Comment by scotteh** [comment]
I agree, thanks for picking that up!
