### ISSUE TITLE
Bug in cleanTitle

### ISSUE THREAD

**Issue by mechanicalgux** [scotteh/php-goose#66]
Great library! Very useful.
I noticed a bug when a page has the same title as the opengraph title, the method cleanTitle() strips everything. As a result $article->getTitle() is empty.

Example of markup to reproduce this bug:
```html
<title>My website</title>
<meta property="og:title" content="My website">
```

https://github.com/scotteh/php-goose/blob/0e1dc6cb3f83c8dcf4d3fae4d393a0f3545f1f0e/src/Modules/Extractors/MetaExtractor.php#L88

**Comment by scotteh** [comment]
Thanks, fixed!
