### ISSUE TITLE
An ability to extract data directly from raw html instead of URL

### ISSUE THREAD

**Issue by DroneZzZko** [scotteh/php-goose#68]
It would be great to be able to extract data from raw html. So I'll give you an example.
I have articles in a DB and I want to extract tags and meta data from those articles without any requests.

**Comment by scotteh** [comment]
This can be done currently, but could really use some improvement. If you pass raw html as the 2nd argument to the [extractContent](https://github.com/scotteh/php-goose/blob/master/src/Client.php#L40) method no requests will be performed.

**Comment by DroneZzZko** [comment]
Works for me. Thanks.
