### ISSUE TITLE
Warning: mb_convert_encoding()

### ISSUE THREAD

**Issue by DroneZzZko** [scotteh/php-goose#69]
Got 

> Warning: mb_convert_encoding(): Illegal character encoding specified in vendor/scotteh/php-dom-wrapper/src/Document.php on line 102

Tried this:

```php
$article = (new Goose\Client(['image_fetch_best' => false]))->extractContent('http://peteflow.blogspot.ru/2007/04/history-of-aol-warez.html');
```

PHP:
```bash
php -v
PHP 7.1.10 (cli) (built: Oct  2 2017 15:53:14) ( NTS )
```

**Comment by oliverhermanni** [comment]
I already have a fix for this. I'll fork php-dom-wrapper and provide the fix asap.

**Comment by scotteh** [comment]
Release a point version of [scotteh/php-dom-wrapper](https://github.com/scotteh/php-dom-wrapper) so a `composer update` should fix this issue.
