### ISSUE TITLE
How to do static installation? Installation without composer?

### ISSUE THREAD

**Issue by Ms-Shaukat** [scotteh/php-goose#72]
I want to know how I can do static installation? as I didn't use composer for any of php project.

**Comment by scotteh** [comment]
While technically possible, It’s not supported. Any reason you won’t use composer?

**Comment by Ms-Shaukat** [comment]
Can you please guide me? How to do that I am unable to do that without composer. I didn't use it lately and now at this crucial point, I don't want dive in it.

**Comment by scotteh** [comment]
You'll need to work out how to do it without composer if that's how you wish to use it.
