### ISSUE TITLE
Warning: mb_convert_encoding(): Unable to detect character encoding

### ISSUE THREAD

**Issue by DroneZzZko** [scotteh/php-goose#73]
Often see this error:

> Unable to detect character encoding in /app/vendor/scotteh/php-dom-wrapper/src/Document.php on line 107

**Comment by scotteh** [comment]
Do you have any sample urls i could review?

**Comment by shaneiseminger** [comment]
@scotteh -- I've run across this at this URL:

https://www.marketingprofs.com/articles/2018/34721/tons-of-traffic-but-few-conversions-three-ideas-for-repurposing-blog-traffic

It seems like this is easy to fix by using the value returned by `mb_detect_encoding` -- if `false`, don't convert. But I'm not completely sure that won't affect other URLs.
