### ISSUE TITLE
Manual is confusing

### ISSUE THREAD

**Issue by ethaniel** [scotteh/php-goose#77]
Hello!

Thank you for the awesome plugin! I would like to mention, that the manual is a bit confusing.
There is no explanation of the inner functions, like getImageSrc(), in your example.

Here is the full example that works:
```
$goose = new GooseClient();
$article = $goose->extractContent("http://...");
$temp = $article->getTopImage();
echo $temp->getImageSrc();
```

Also, I'd be more than happy to send you some $$. Do you have paypal?

**Comment by scotteh** [comment]
Glad you find it useful!

The documentation is sorely lacking, something to look into when I have a chance.

Leaving this issue open for the time being.
