### ISSUE TITLE
fatal error during implementation

### ISSUE THREAD

**Issue by akash-0001gupta** [scotteh/php-goose#79]
I am facing fatal error while implementing library.
here is my code - 
<?php
require('vendor/autoload.php');
use Goose\Client as GooseClient;

$goose = new GooseClient();
$article = $goose->extractContent('https://www.apachefriends.org/');

$title = $article->getTitle();
$metaDescription = $article->getMetaDescription();
$metaKeywords = $article->getMetaKeywords();
$canonicalLink = $article->getCanonicalLink();
$domain = $article->getDomain();
$tags = $article->getTags();
$links = $article->getLinks();
$videos = $article->getVideos();
$articleText = $article->getCleanedArticleText();
$entities = $article->getPopularWords();
$image = $article->getTopImage();
$allImages = $article->getAllImages();

?>

Error- 
Fatal error: Uncaught TypeError: Argument 2 passed to DOMWrap\Element::attr() must be of the type string or null, float given, called in C:\xampp\htdocs\test\vendor\scotteh\php-goose\src\Traits\NodeGravityTrait.php on line 35 and defined in C:\xampp\htdocs\test\vendor\scotteh\php-dom-wrapper\src\Traits\ManipulationTrait.php:380 Stack trace: #0 C:\xampp\htdocs\test\vendor\scotteh\php-goose\src\Traits\NodeGravityTrait.php(35): DOMWrap\Element->attr('gravityScore', 55) #1 C:\xampp\htdocs\test\vendor\scotteh\php-goose\src\Modules\Extractors\ContentExtractor.php(115): Goose\Modules\Extractors\ContentExtractor->updateScore(Object(DOMWrap\Element), 55) #2 C:\xampp\htdocs\test\vendor\scotteh\php-goose\src\Modules\Extractors\ContentExtractor.php(168): Goose\Modules\Extractors\ContentExtractor->calculateBestNodeCandidateScores(Object(DOMWrap\Element), 55) #3 C:\xampp\htdocs\test\vendor\scotteh\php-goose\src\Modules\Extractors\ContentExtractor.php(23): Goose\Modules\Extractors\ContentExtractor->getTopNode() #4 C:\xampp\htdocs\test\v in C:\xampp\htdocs\test\vendor\scotteh\php-dom-wrapper\src\Traits\ManipulationTrait.php on line 380

Please hep me.

**Comment by scotteh** [comment]
Thanks for the bug report. Packaged a new version of the scotteh/php-dom-wrapper dependency. Running `composer update` should fix the issue.

**Comment by akash-0001gupta** [comment]
Thanks for the update. i was just testing it on a website - 'https://www.google.com' . Library return an empty array of tags, links and videos. Can you please look into this.

**Comment by scotteh** [comment]
If you view the source of google.com you'll see it's mostly javascript with hardly any actual content to extract.
