### ISSUE TITLE
Version 1.0.3 does not work after upgrade from 0.6.4

### ISSUE THREAD

**Issue by Isinlor** [scotteh/php-goose#81]
Hello,

first of all great library! 👍 

Unfortunately, the new version 1.0.* does not work at all due to the strict types.

Here is my test scenario (PHP 7.1.4), I have pulled the repository and created an example.php file:
```php
<?php

use Goose\Client as GooseClient;

require('vendor/autoload.php');

$goose = new GooseClient();
$article = $goose->extractContent($_GET['article']);
```

It breaks down on every URL that I test e.g.:

> https://qz.com/1220576/the-race-to-build-a-self-driving-car-charted/
> Fatal error: **Uncaught TypeError: Argument 1 passed to Goose\Images\ImageUtils::getFileExtensionName() must be an instance of Goose\Images\object, instance of stdClass given**, called in /php-goose/src/Images/ImageUtils.php on line 63 and defined in /php-goose/src/Images/ImageUtils.php on line 75

> https://www.learningjquery.com/2017/10/12-awesome-jquery-virtual-keyboard-plugins-2
> Warning: **Division by zero in /php-goose/src/Traits/NodeCommonTrait.php on line 46**

**Comment by scotteh** [comment]
Thanks for the bug report! Latest version fixes these issues. `composer update` and you should be good to go.
