### ISSUE TITLE
Type error: trim() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by aakar** [scotteh/php-goose#82]
Seeing this:
```
In MetaExtractor.php line 179:

  Type error: trim() expects parameter 1 to be string, null given
```

I'm trying to load the following URL: https://www.newyorker.com/magazine/2018/03/19/the-man-whos-helped-elon-musk-tom-brady-and-ari-emanuel-get-dressed

Should there be a check to see if $content is null before trying to trim it?

**Comment by scotteh** [comment]
Published a new version that fixes this. `composer update` and you should be good to go!
