### ISSUE TITLE
Fatal error on articles embedding local media

### ISSUE THREAD

**Issue by Triqueon** [scotteh/php-goose#89]
When trying to analyze an article that has an embedded resource (via iframe, embed or object tags) that is embedded via a relative link (i.e. src="/media/video1.mpg"), the analysis dies, because `getVideos()` in AdditionalDataExtractor.php cannot parse the URL and ends up doing a `preg_match('something', null)` in line 89, which leads to a fatal error in most php configurations.

Possible Solutions include:
1) Checking for `empty($srcHost)` after the parsing is done and aborting if true
2) Checking for `empty($srcHost)` after the parsing and assuming `$srcHost` is identical to the article Host if true
3) Checking for `substr($src, '/') === 0` (note the ===, a simple == will get you in trouble) and assuming `$srcHost` is identical to the article Host if true

If you want, I can fix up a PR for one of the above scenarios, I just don't know which is the preferred option.

**Comment by scotteh** [comment]
Cheers for picking this up. Updated this method to also return videos based on file type match.
