### ISSUE TITLE
Type error: DateTime::__construct() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by mfprogrammer** [scotteh/php-goose#90]
` 
        // Check for JSON-LD
        $nodes = $this->article()->getRawDoc()->find('script[type="application/ld+json"]');
 
        /* @var $node Element */
        foreach ($nodes as $node) {
            try {
                $json = json_decode($node->text());
                if (isset($json->datePublished)) {
                    $dt = new \DateTime($json->datePublished);
                    break;
                }
            }
            catch (\Exception $e) {
                // Do nothing here in case the node has unrecognizable date information.
            }
        }
 
        return $dt;
    }
 
    /**
     * Check for and determine dates based on Dublin Core standards.
     *`

The below url throws that error. Thre needs to be a check for string variable and if it gets an array, it needs to be converted to a string.

https://uk.mobile.reuters.com/news/picture/world-cup-opening-ceremony-idUKRTX692ZC

Error is in this file:
scotteh/php-goose/src/Modules/Extractors/PublishDateExtractor.php on line 111

**Comment by zerofill** [comment]
Find a solution to this?
