### ISSUE TITLE
"Best Guess" Function

### ISSUE THREAD

**Issue by frisch1** [scotteh/php-goose#91]
First, thanks very much for this port. Super easy to use, much appreciated.

I had a question in regard to the ContentExtractor.php. I want to try to use this to get the articleHTML for lists. An example of a page with a list would be here:
https://agriculture.house.gov/calendar/?Timeframe=All

The trick (as near as I can tell) is the main body isn't scoring high enough to be captured as a candidate, thus it returns an empty htmlArticle.

My question: is there a way / method that, in the config (or another approach), we could tell the extractor to give its best guess, even if the score is low?

Also, I could be completely misinterpreting the code, and if so, apologies.

**Comment by scotteh** [comment]
This library is geared towards textual content extraction. You would be better served using a library that allows targeted content extraction. php-dom-wrapper is a fairly simple jQuery style wrapper around the PHP DOMDocument class allows for this (Goose uses it under the hood).

Example:
``` php
use DOMWrap\Document;

$doc = new Document();
$doc->html(file_get_contents('...'));
$doc->find('ul > li')->each(function($node){
    $link = $node->find('a')->first();

    echo $link->text() . ' => ' . $link->attr('href') . '<br>';
});
```
