### ISSUE TITLE
`Goose\Traits\NodeGravityTrait::updateScore` calls `DOMWrap\Element::attr()` with invalid type

### ISSUE THREAD

**Issue by inanimatt** [scotteh/php-goose#92]
I'm calling `$client->extractContent($url)` and getting a fatal error:

```
Type error: Argument 2 passed to DOMWrap\Element::attr() must be of the type string or null, float given, called in /var/www/app/vendor/scotteh/php-goose/src/Traits/NodeGravityTrait.php on line 35
```

Looking at that method (and I suspect also `updateNodeCount()` below it, though I've not confirmed that), it casts the current value of that attribute to an integer, then tries to set it again as a float, though only null and string types are allowed.

Happy to do a PR for this, except I'm not sure what the behaviour _should_ be – cast the float to a string, or cast it to an integer and then a string? Or perhaps this is an issue with the DOMWrap class instead (I'd guess not, though).

**Comment by scotteh** [comment]
Cheers for the bug report. Released a new 1.0.8 version with this fix.
