### ISSUE TITLE
Don't parsing text from Webarhive

### ISSUE THREAD

**Issue by shushik81** [scotteh/php-goose#98]
Don't parsing text from webarhive on russian
here example url to page
https://web.archive.org/web/http://worldwomens.ru/anomal/42-anomalii-stroenija-polovykh-organov-i.html
in my opinion the issue start on function getTopNodeByScore
because the script incorrectly defines this parameter and returns the wrong node after that
and on thr end of script return empty string like that "\n\n\n\n\n\n\n\n\n\n\n\n"
Hope you fix it.
Thanks

**Comment by scotteh** [comment]
Pushed a fix for this with v1.0.10.
